version: "3.9"
services:
  db:
    image: mysql:5.7.40-debian
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 8bwh9P6bDZRNYGFm
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: 8bwh9P6bDZRNYGFm
    volumes:
      - db_data:/var/lib/mysql
      - ./database/dbDeploy/EcommerceWebSite.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "80:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER:  ecommerce
      DB_PASSWORD: 8bwh9P6bDZRNYGFm
      DB_WORKING: ecommerce

volumes:
  db_data: