version: "3.9"
services:
  db:
    image: mysql:8.0.31-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 8bwh9P6bDZRNYGFm
      MYSQL_DATABASE: ecommerce
    volumes:
      - db_data:/var/lib/mysql
      - ./database/dbDeploy/EcommerceWebSite.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build: .
    restart: always
    ports:
      - "80:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 8bwh9P6bDZRNYGFm
      DB_WORKING: ecommerce
